# Generated by Django 6.0 on 2025-12-22 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveField(
            model_name='betsettings',
            name='created_at',
        ),
        migrations.AddField(
            model_name='room',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='turn_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='betsettings',
            name='max_bet',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='betsettings',
            name='min_bet',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='betsettings',
            name='step',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_turn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='secret_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('finished', 'Finished')], db_index=True, default='open', max_length=12),
        ),
        migrations.DeleteModel(
            name='AccountTransaction',
        ),
    ]
