# Generated by Django 6.0 on 2025-12-22 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_room_options_remove_betsettings_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='betsettings',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='betsettings',
            name='max_bet',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='betsettings',
            name='min_bet',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='betsettings',
            name='step',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_current_turn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='secret_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('finished', 'Finished')], db_index=True, default='open', max_length=16),
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bet_lock', 'Bet lock'), ('payout', 'Payout'), ('adjust', 'Adjust')], db_index=True, max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='game.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
